config/routes.rb
Rails.application.routes.draw do
  resources :participantes
  resources :users
  resources :partidas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participante.rb
class Participante < ApplicationRecord
  has_many :user
  has_many :partida

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :partida
end

app/models/partida.rb
class Partida < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/participantes_controller.rb
class ParticipantesController < ApplicationController
  before_action :set_participante, only: [:show, :edit, :update, :destroy]

  # GET /participantes
  # GET /participantes.json
  def index
    @participantes = Participante.all
  end

  # GET /participantes/1
  # GET /participantes/1.json
  def show
  end

  # GET /participantes/new
  def new
    @participante = Participante.new
  end

  # GET /participantes/1/edit
  def edit
  end

  # POST /participantes
  # POST /participantes.json
  def create
    @participante = Participante.new(participante_params)

    respond_to do |format|
      if @participante.save
        format.html { redirect_to @participante, notice: 'Participante was successfully created.' }
        format.json { render :show, status: :created, location: @participante }
      else
        format.html { render :new }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participantes/1
  # PATCH/PUT /participantes/1.json
  def update
    respond_to do |format|
      if @participante.update(participante_params)
        format.html { redirect_to @participante, notice: 'Participante was successfully updated.' }
        format.json { render :show, status: :ok, location: @participante }
      else
        format.html { render :edit }
        format.json { render json: @participante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participantes/1
  # DELETE /participantes/1.json
  def destroy
    @participante.destroy
    respond_to do |format|
      format.html { redirect_to participantes_url, notice: 'Participante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participante
      @participante = Participante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participante_params
      params.require(:participante).permit(:user_id, :partida_id)
    end
end

app/controllers/partidas_controller.rb
class PartidasController < ApplicationController
  before_action :set_partida, only: [:show, :edit, :update, :destroy]

  # GET /partidas
  # GET /partidas.json
  def index
    @partidas = Partida.all
  end

  # GET /partidas/1
  # GET /partidas/1.json
  def show
  end

  # GET /partidas/new
  def new
    @partida = Partida.new
  end

  # GET /partidas/1/edit
  def edit
  end

  # POST /partidas
  # POST /partidas.json
  def create
    @partida = Partida.new(partida_params)

    respond_to do |format|
      if @partida.save
        format.html { redirect_to @partida, notice: 'Partida was successfully created.' }
        format.json { render :show, status: :created, location: @partida }
      else
        format.html { render :new }
        format.json { render json: @partida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partidas/1
  # PATCH/PUT /partidas/1.json
  def update
    respond_to do |format|
      if @partida.update(partida_params)
        format.html { redirect_to @partida, notice: 'Partida was successfully updated.' }
        format.json { render :show, status: :ok, location: @partida }
      else
        format.html { render :edit }
        format.json { render json: @partida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partidas/1
  # DELETE /partidas/1.json
  def destroy
    @partida.destroy
    respond_to do |format|
      format.html { redirect_to partidas_url, notice: 'Partida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partida
      @partida = Partida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partida_params
      params.require(:partida).permit(:title, :description, :local, :data_partida)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participantes_helper.rb
module ParticipantesHelper
end

app/helpers/partidas_helper.rb
module PartidasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Esport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participantes/_form.html.erb
<%= form_with(model: participante, local: true) do |form| %>
  <% if participante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participante.errors.count, "error") %> prohibited this participante from being saved:</h2>

      <ul>
      <% participante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :participante_user_id %>
  </div>

  <div class="field">
    <%= form.label :partida_id %>
    <%= form.text_field :partida_id, id: :participante_partida_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participantes/edit.html.erb
<h1>Editing Participante</h1>

<%= render 'form', participante: @participante %>

<%= link_to 'Show', @participante %> |
<%= link_to 'Back', participantes_path %>

app/views/participantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participantes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Partida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participantes.each do |participante| %>
      <tr>
        <td><%= participante.user %></td>
        <td><%= participante.partida %></td>
        <td><%= link_to 'Show', participante %></td>
        <td><%= link_to 'Edit', edit_participante_path(participante) %></td>
        <td><%= link_to 'Destroy', participante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participante', new_participante_path %>

app/views/participantes/new.html.erb
<h1>New Participante</h1>

<%= render 'form', participante: @participante %>

<%= link_to 'Back', participantes_path %>

app/views/participantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @participante.user %>
</p>

<p>
  <strong>Partida:</strong>
  <%= @participante.partida %>
</p>

<%= link_to 'Edit', edit_participante_path(@participante) %> |
<%= link_to 'Back', participantes_path %>

app/views/partidas/_form.html.erb
<%= form_with(model: partida, local: true) do |form| %>
  <% if partida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(partida.errors.count, "error") %> prohibited this partida from being saved:</h2>

      <ul>
      <% partida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :partida_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :partida_description %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local, id: :partida_local %>
  </div>

  <div class="field">
    <%= form.label :data_partida %>
    <%= form.datetime_select :data_partida, id: :partida_data_partida %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/partidas/edit.html.erb
<h1>Editing Partida</h1>

<%= render 'form', partida: @partida %>

<%= link_to 'Show', @partida %> |
<%= link_to 'Back', partidas_path %>

app/views/partidas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Partidas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Local</th>
      <th>Data partida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partidas.each do |partida| %>
      <tr>
        <td><%= partida.title %></td>
        <td><%= partida.description %></td>
        <td><%= partida.local %></td>
        <td><%= partida.data_partida %></td>
        <td><%= link_to 'Show', partida %></td>
        <td><%= link_to 'Edit', edit_partida_path(partida) %></td>
        <td><%= link_to 'Destroy', partida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partida', new_partida_path %>

app/views/partidas/new.html.erb
<h1>New Partida</h1>

<%= render 'form', partida: @partida %>

<%= link_to 'Back', partidas_path %>

app/views/partidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @partida.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @partida.description %>
</p>

<p>
  <strong>Local:</strong>
  <%= @partida.local %>
</p>

<p>
  <strong>Data partida:</strong>
  <%= @partida.data_partida %>
</p>

<%= link_to 'Edit', edit_partida_path(@partida) %> |
<%= link_to 'Back', partidas_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>